<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} | Shahzad Ali</title><meta name="description" content="{{ $description }}"><link rel="icon" type="image/svg+xml" href="{{ route('profile.favicon') }}">
    <link rel="canonical" href="{{ url()->current() }}">
    @if(file_exists(public_path('build/manifest.json'))) @vite(['resources/css/app.css','resources/js/app.js']) @else <link rel="stylesheet" href="{{ route('portfolio.css') }}"> @endif
    <link rel="stylesheet" href="{{ route('portfolio.pages.css') }}">
    <style>
        body.portfolio-shell{background:#0f0f0e;color:#e8e5dd}.portfolio-shell .nav{border-color:#ffffff18}.portfolio-shell .brand,.portfolio-shell .serif,.portfolio-shell h1,.portfolio-shell h2,.portfolio-shell h3{color:#fff}.portfolio-shell .nav-links,.portfolio-shell .section-intro,.portfolio-shell p{color:#aaa79f}.portfolio-shell .nav-links a:hover,.portfolio-shell a:hover{color:#fff}.portfolio-shell .nav-cta,.portfolio-shell .btn-coral{background:#cc785c;color:#fff}.portfolio-shell .cream-band{background:#171614}.portfolio-shell .feature,.portfolio-shell .detail-card,.portfolio-shell .service{background:#1b1a18;border-color:#ffffff18;color:#aaa79f}.portfolio-shell .feature h3,.portfolio-shell .detail-card h3,.portfolio-shell .service h3{color:#fff}.portfolio-shell .project{background:#171614;border-color:#ffffff1c}.portfolio-shell .project-body h3{color:#fff}.portfolio-shell .project-body p{color:#aaa79f}.portfolio-shell .tag{background:#24221f;border:1px solid #ffffff20;color:#e8e5dd}.portfolio-shell .tag:hover{background:#3a2119;border-color:#cc785c;color:#ffd8cc}.portfolio-shell .page-band,.portfolio-shell .code-band,.portfolio-shell .footer{background:#0a0a09}.portfolio-shell .project-visual,.portfolio-shell .project-copy,.portfolio-shell .project-meta,.portfolio-shell .project-features{color:#aaa79f}.portfolio-shell .project-copy h2{color:#fff}.portfolio-shell .project-meta{border-color:#ffffff18}.portfolio-shell .back-link,.portfolio-shell .section-label,.portfolio-shell .number{color:#cc785c}.portfolio-shell .contact{background:#8f4f3d}.portfolio-shell .field input,.portfolio-shell .field textarea{color:#fff}.portfolio-shell .footer{border-top:1px solid #ffffff12}
    </style>
</head>
<body class="portfolio-shell">
    <header class="shell nav"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">✳</span>Shahzad Ali</a><button class="menu" data-menu aria-label="Toggle navigation">☰</button><nav class="nav-links" data-links><a href="{{ route('about') }}">About</a><a href="{{ route('skills') }}">Skills</a><a href="{{ route('portfolio') }}">Projects</a><a href="{{ route('services') }}">Services</a><a href="{{ route('experience') }}">Journey</a><a class="nav-cta" href="{{ route('contact') }}">Let’s talk</a></nav></header>
    <main>@yield('content')</main>
    <footer class="footer"><div class="shell"><div class="footer-grid"><div><a class="brand" href="{{ route('home') }}"><span class="brand-mark">✳</span>Shahzad Ali</a><p style="margin-top:18px;max-width:240px">A full-stack developer in progress, making the web a little more human.</p></div><div><h3>Explore</h3><a href="{{ route('about') }}">About</a><a href="{{ route('skills') }}">Skills</a><a href="{{ route('portfolio') }}">Projects</a></div><div><h3>Services</h3><a href="{{ route('services') }}">What I do</a><a href="{{ route('experience') }}">Journey</a><a href="{{ route('contact') }}">Contact</a></div><div><h3>Elsewhere</h3><a href="https://github.com" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://linkedin.com" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://www.fiverr.com/" target="_blank" rel="noopener noreferrer"><span class="brand-mark" aria-hidden="true"></span>Fiverr ↗</a><a href="mailto:{{ config('mail.from.address') }}">{{ config('mail.from.address') }} ↗</a></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Shahzad Ali</span><span>Designed with warmth · Built with Laravel</span></div></div></footer>
</body>
</html>
