<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ $title }} | Shahzad Ali</title><meta name="description" content="{{ $description }}"><link rel="icon" type="image/svg+xml" href="{{ route('profile.favicon') }}">
    <link rel="canonical" href="{{ url()->current() }}">
    @if(file_exists(public_path('build/manifest.json'))) @vite(['resources/css/app.css','resources/js/app.js']) @else <link rel="stylesheet" href="{{ route('portfolio.css') }}"> @endif
    <link rel="stylesheet" href="{{ route('portfolio.pages.css') }}">
    <style>
        body.portfolio-shell{background:#08080a;color:#d4d4d8}body.portfolio-shell::before{content:'';position:fixed;inset:0;pointer-events:none;z-index:0;background-image:radial-gradient(rgba(255,255,255,.07) 1px,transparent 1px);background-size:24px 24px;mask-image:radial-gradient(ellipse at top,black 30%,transparent 75%)}main,header,footer{position:relative;z-index:1}.portfolio-shell .nav{border-color:#27272a}.portfolio-shell .brand,.portfolio-shell .serif,.portfolio-shell h1,.portfolio-shell h2,.portfolio-shell h3{color:#fff}.portfolio-shell .nav-links,.portfolio-shell .section-intro,.portfolio-shell p{color:#a1a1aa}.portfolio-shell .nav-links a:hover,.portfolio-shell a:hover{color:#f43f5e}.portfolio-shell .nav-cta,.portfolio-shell .btn-coral{background:linear-gradient(135deg,#f43f5e,#fb923c);color:#fff;border:1px solid rgba(255,255,255,.18);box-shadow:0 0 20px rgba(244,63,94,.35)}.portfolio-shell .cream-band{background:#0e0e12}.portfolio-shell .feature,.portfolio-shell .detail-card,.portfolio-shell .service{background:rgba(24,24,27,.6);backdrop-filter:blur(12px);border:1px solid rgba(63,63,70,.8);border-radius:1rem;color:#a1a1aa;transition:border-color .3s,box-shadow .3s}.portfolio-shell .feature:hover,.portfolio-shell .detail-card:hover,.portfolio-shell .service:hover{border-color:#71717a;box-shadow:0 0 30px rgba(244,63,94,.08)}.portfolio-shell .feature h3,.portfolio-shell .detail-card h3,.portfolio-shell .service h3{color:#fff}.portfolio-shell .project{background:rgba(24,24,27,.6);backdrop-filter:blur(12px);border:1px solid rgba(63,63,70,.8);border-radius:1rem;transition:border-color .3s,box-shadow .3s}.portfolio-shell .project:hover{border-color:#71717a;box-shadow:0 0 30px rgba(244,63,94,.08)}.portfolio-shell .project-body h3{color:#fff}.portfolio-shell .project-body p{color:#a1a1aa}.portfolio-shell .tag{background:#18181b;border:1px solid #3f3f46;color:#d4d4d8}.portfolio-shell .tag:hover{background:#3f1d24;border-color:#f43f5e;color:#fecdd3}.portfolio-shell .page-band,.portfolio-shell .code-band,.portfolio-shell .footer{background:#0a0a0e}.portfolio-shell .project-visual,.portfolio-shell .project-copy,.portfolio-shell .project-meta,.portfolio-shell .project-features{color:#a1a1aa}.portfolio-shell .project-copy h2{color:#fff}.portfolio-shell .project-meta{border-color:#27272a}.portfolio-shell .back-link,.portfolio-shell .section-label,.portfolio-shell .number{color:#f43f5e}.portfolio-shell .contact{background:rgba(24,24,27,.7);backdrop-filter:blur(12px);border:1px solid rgba(63,63,70,.8);border-radius:1rem}.portfolio-shell .field input,.portfolio-shell .field textarea{color:#fff;background:rgba(255,255,255,.05);border-color:#3f3f46}.portfolio-shell .footer{border-top:1px solid #27272a}
    </style>
</head>
<body class="portfolio-shell">
    <header class="shell nav"><a class="brand" href="{{ route('home') }}"><span class="brand-mark">✳</span>Shahzad Ali</a><button class="menu" data-menu aria-label="Toggle navigation">☰</button><nav class="nav-links" data-links><a href="{{ route('about') }}">About</a><a href="{{ route('skills') }}">Skills</a><a href="{{ route('portfolio') }}">Projects</a><a href="{{ route('services') }}">Services</a><a href="{{ route('experience') }}">Journey</a><a class="nav-cta" href="{{ route('contact') }}">Let’s talk</a></nav></header>
    <main>@yield('content')</main>
    <footer class="footer"><div class="shell"><div class="footer-grid"><div><a class="brand" href="{{ route('home') }}"><span class="brand-mark">✳</span>Shahzad Ali</a><p style="margin-top:18px;max-width:240px">A full-stack developer in progress, making the web a little more human.</p></div><div><h3>Explore</h3><a href="{{ route('about') }}">About</a><a href="{{ route('skills') }}">Skills</a><a href="{{ route('portfolio') }}">Projects</a></div><div><h3>Services</h3><a href="{{ route('services') }}">What I do</a><a href="{{ route('experience') }}">Journey</a><a href="{{ route('contact') }}">Contact</a></div><div><h3>Elsewhere</h3><a href="https://github.com" target="_blank" rel="noopener noreferrer">GitHub ↗</a><a href="https://linkedin.com" target="_blank" rel="noopener noreferrer">LinkedIn ↗</a><a href="https://www.fiverr.com/" target="_blank" rel="noopener noreferrer"><span class="brand-mark" aria-hidden="true"></span>Fiverr ↗</a><a href="mailto:{{ config('mail.from.address') }}">{{ config('mail.from.address') }} ↗</a></div></div><div class="footer-bottom"><span>© {{ date('Y') }} Shahzad Ali</span><span>Designed with warmth · Built with Laravel</span></div></div></footer>
</body>
</html>
